name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0
      - name: Inspect(lint, typecheck, test)
        run: yarn inspect
